# Generated by Django 3.1.1 on 2020-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200908_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100),
        ),
    ]
